conda activate acc-sim
export CX_DATA_HOME="/workspace/data"
# export CX_PROJECT_HOME="/home/cx922/Coprocessor_for_Llama"
# export CUDA_DEVICE="2,3"
# export PROC_NUM="2"
export HF_DATASETS_CACHE="${CX_DATA_HOME}/datasets"
export HF_HOME="${CX_DATA_HOME}/hf_home"
export HF_HUB="${CX_DATA_HOME}/hf_hub"
export TRANSFORMERS_CACHE="${CX_DATA_HOME}/models"
export HF_HUB_CACHE="${CX_DATA_HOME}/hf_hub/.cache"
