conda activate acc-sim
export CX_DATA_HOME="/data/models/cx922"
export CX_PROJECT_HOME="/home/cx922/Coprocessor_for_Llama"
export CUDA_DEVICE="2,3"
export PROC_NUM="2"
export HF_DATASETS_CACHE="/data/datasets"
export HF_HOME="/data/"
export TRANSFORMERS_CACHE="${CX_DATA_HOME}/hf_transformers"
export HF_HUB_CACHE="${CX_DATA_HOME}/hf_hub"
export HF_HUB="/data/hf_hub"
