# This Dockerfile configures a Docker environment that
# contains all the required packages for the tool
FROM ubuntu:24.04

USER root

# Install apt packages 
ADD install-pkgs.sh install-pkgs.sh
RUN bash install-pkgs.sh
CMD ["bash"]

# Install pip packages 
# ADD install-pips.sh install-pips.sh
# RUN bash install-pips.sh