# This Dockerfile configures a Docker environment that
# contains all the required packages for the tool
FROM ubuntu:22.04

USER root

# Install apt packages 
ADD install-pkgs.sh install-pkgs.sh
RUN bash install-pkgs.sh
CMD ["bash"]

# Install pip packages 
ADD install-pips.sh install-pips.sh
RUN bash install-pips.sh

# Add environment variables
# ADD install-env.sh install-env.sh
# RUN bash install-env.sh $VHLS_PATH $VHLS_VERSION
