name: acc-sim
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - numpy
  - pandas
  - toml
  - pip:
      - torch
      - torchvision
      - torchaudio
      - jsonargparse[all]
      - lm-eval==0.4.8
      - transformers==4.57.6
      - datasets
      - evaluate
      - accelerate
      - peft
      - scikit-learn
      - matplotlib
      - tqdm
      - sentencepiece
      - protobuf
      - einops
      # dse related, temporary placement for now
      - botorch==0.9.5
      - optuna-integration==4.4.0
      - optuna==4.4.0
      - plotly==6.2.0
      # add mase-triton with current tag 0.0.5
      - mase-triton==0.0.5
