name: acc-sim
channels:
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - numpy
  - pandas
  - toml
  - pip:
      - torch --index-url https://download.pytorch.org/whl/cu128
      - torchvision --index-url https://download.pytorch.org/whl/cu128
      - torchaudio --index-url https://download.pytorch.org/whl/cu128
      - jsonargparse[all]
      - lm-eval==0.4.8
      - transformers==4.52.4
      - datasets
      - evaluate
      - accelerate
      - peft
      - scikit-learn
      - matplotlib
      - tqdm
      - sentencepiece
      - protobuf
      - colorlog