
; Generated assembly code for LLM model
; Model: AICrossSim/clm-60m
; Architecture: LlamaForCausalLM
; Hidden size: 384
; Number of layers: 22
; Generated by LLM Compiler


; === embed_tokens (embedding) ===
; Embedding lookup: vocab_size=49152, embedding_dim=384
; Input: token_ids, Output: embedded_vectors
TODO: fill me

; === layer_0_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_0_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_0_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_0_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_0_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_0_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_1_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_1_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_1_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_1_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_1_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_1_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_2_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_2_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_2_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_2_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_2_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_2_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_3_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_3_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_3_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_3_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_3_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_3_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_4_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_4_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_4_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_4_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_4_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_4_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_5_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_5_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_5_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_5_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_5_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_5_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_6_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_6_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_6_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_6_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_6_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_6_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_7_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_7_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_7_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_7_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_7_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_7_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_8_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_8_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_8_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_8_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_8_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_8_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_9_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_9_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_9_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_9_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_9_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_9_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_10_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_10_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_10_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_10_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_10_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_10_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_11_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_11_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_11_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_11_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_11_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_11_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_12_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_12_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_12_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_12_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_12_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_12_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_13_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_13_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_13_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_13_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_13_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_13_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_14_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_14_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_14_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_14_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_14_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_14_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_15_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_15_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_15_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_15_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_15_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_15_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_16_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_16_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_16_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_16_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_16_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_16_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_17_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_17_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_17_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_17_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_17_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_17_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_18_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_18_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_18_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_18_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_18_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_18_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_19_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_19_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_19_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_19_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_19_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_19_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_20_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_20_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_20_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_20_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_20_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_20_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_21_input_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_21_self_attn (attention) ===
; Self-attention: hidden_size=384, num_heads=6, head_dim=64
; Q, K, V projections and attention computation

; Attention-specific optimizations
TODO: fill me

; === layer_21_attn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === layer_21_post_attention_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

; === layer_21_mlp (ffn) ===
; FFN/MLP: hidden_size=384, intermediate_size=1408, activation=silu
; Gate and Up projections

; FFN operations
TODO: fill me

; === layer_21_ffn_residual (elementwise_add) ===
; Elementwise addition (residual connection): shape=[384]
; Add two tensors element-wise
TODO: fill me

; === final_layernorm (normalization) ===
; RMS Normalization: normalized_shape=384, eps=1e-05
; Compute RMS and normalize
TODO: fill me

    ; Program termination
