[CONFIG.BLEN]
active = 8
SIMULATION = 8
ASIC = 8
default = 4
tunable_range = [ 2, 4, 8, 16, 32]

[CONFIG.MLEN]
active = 16
SIMULATION = 128
ASIC = 16
default = 8
tunable_range = [ 2, 4, 8, 16, 32, 64, 128, 256, 512]

[CONFIG.VLEN]
active = 16
SIMULATION = 128
ASIC = 16
default = 8
tunable_range = [ 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]

[CONFIG.HBM_M_Prefetch_Amount]
active = 16
SIMULATION = 8
ASIC = 16
default = 8
tunable_range = [ 2, 4, 8, 16, 32, 64, 128, 256,]

[CONFIG.HBM_V_Prefetch_Amount]
active = 16
SIMULATION = 8
ASIC = 16
default = 8
tunable_range = [ 2, 4, 8, 16, 32, 64, 128, 256,]

[CONFIG.HBM_V_Writeback_Amount]
active = 16
SIMULATION = 8
ASIC = 16
default = 8
tunable_range = [ 2, 4, 8, 16, 32, 64, 128, 256,]

[PRECISION.ACT_ELEMENT_WIDTH]
active = 8
SIMULATION = 8
ASIC = 8
default = 8
tunable_range = [ "MXINT_2", "MXINT_4", "MXINT_8", "MXFP_E3M4", "MXFP_E4M3", "MXFP_E5M2"]

[PRECISION.KV_ELEMENT_WIDTH]
active = 8
SIMULATION = 8
ASIC = 8
default = 8
tunable_range = [ "MXINT_2", "MXINT_4", "MXINT_8", "MXFP_E3M4", "MXFP_E4M3", "MXFP_E5M2"]

[PRECISION.FP_SETTING]
active = 7
SIMULATION = 7
ASIC = 8
default = 7
tunable_range = [ "FP_E6M5", "FP_E5M6", "FP_E4M7", "FP_E8M5"]

[PRECISION.FP_EXP_WIDTH]
active = 7
SIMULATION = 7
ASIC = 8
default = 7
tunable_range = [ 2, 3, 4, 5, 6, 7, 8,]

[PRECISION.FP_MANT_WIDTH]
active = 8
SIMULATION = 8
ASIC = 7
default = 8
tunable_range = [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,]

[PRECISION.INT_DATA_WIDTH]
active = 32
SIMULATION = 32
ASIC = 32
default = 32
tunable_range = [ 16, 32, 64,]

